### ISSUE TITLE
can run at dart version in latest version.

### ISSUE THREAD

**Issue by markchiuleo** [iteqno-id/fluboard#15]
m@raspberrypi:~/source/fluboard $ flutter build linux
Resolving dependencies... 
The current Dart SDK version is 3.5.3.

Because fluboard requires SDK version >=2.17.6 <3.0.5, version solving failed.

**Comment by f1dz** [comment]
Hi @markchiuleo 
Since my monitor was broken, I am no longer updating the project until now.

Have you tried [Flutter Version Management](https://fvm.app) to manage multiple versions of Dart/Flutter SDK?
Give it a try 😉

**Comment by markchiuleo** [comment]
ok. but I find run the command. it fine.
flutter pub upgrade --major-versions
